'use client'

import { useEffect, useState } from 'react'
import { Check, Copy, ChevronDown, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

type BuyDialogProps = { open: boolean; onClose: () => void; amount: string; price: number }
type Payment = { orderNumber: string; paymentId: string; payAddress?: string; payAmount?: number; payCurrency?: string; amount: string; priceUsd: number }
const POPULAR = ['btc', 'ltc', 'eth', 'doge', 'sol', 'trx', 'usdttrc20', 'usdc']
const FALLBACK = [...POPULAR, 'bnb', 'xmr', 'ton', 'ada']
function amountToMillions(amount: string) { const value = Number.parseFloat(amount.replace('B', '')); return amount.includes('B') ? Math.round(value * 1000) : Math.round(value) }
function label(currency: string) { return currency.toUpperCase() === 'USDTTRC20' ? 'USDT · TRON' : currency.toUpperCase() }

export function BuyDialog({ open, onClose, amount, price }: BuyDialogProps) {
  const [username, setUsername] = useState(''); const [currency, setCurrency] = useState('btc'); const [currencies, setCurrencies] = useState(FALLBACK)
  const [showOther, setShowOther] = useState(false); const [payment, setPayment] = useState<Payment | null>(null); const [status, setStatus] = useState('waiting'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [copied, setCopied] = useState(false)
  useEffect(() => { if (open) { setUsername(''); setPayment(null); setStatus('waiting'); setError(''); setCopied(false); setShowOther(false); fetch('/api/payments/currencies').then((r) => r.json()).then((data) => setCurrencies(data.currencies?.length ? [...new Set([...POPULAR, ...data.currencies])] : FALLBACK)).catch(() => setCurrencies(FALLBACK)) } }, [open])
  useEffect(() => { const onKey = (e: KeyboardEvent) => e.key === 'Escape' && onClose(); if (open) document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey) }, [open, onClose])
  useEffect(() => { if (!payment?.paymentId || ['finished', 'confirmed', 'failed', 'expired', 'refunded'].includes(status)) return; const timer = window.setInterval(async () => { const response = await fetch(`/api/payments/create?paymentId=${encodeURIComponent(payment.paymentId)}`); if (response.ok) setStatus((await response.json()).paymentStatus) }, 5000); return () => window.clearInterval(timer) }, [payment, status])
  if (!open) return null
  const otherCurrencies = currencies.filter((item) => !POPULAR.includes(item))
  async function startPayment(event: React.FormEvent) { event.preventDefault(); setError(''); setLoading(true); try { const response = await fetch('/api/payments/create', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ign: username, amountM: amountToMillions(amount), payCurrency: currency }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPayment(data) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to start payment.') } finally { setLoading(false) } }
  async function copyAddress() { if (!payment?.payAddress) return; await navigator.clipboard.writeText(payment.payAddress); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-label={`Buy ${amount} DonutSMP money`}>
    <button aria-label="Close checkout" className="absolute inset-0 bg-background/80 backdrop-blur-sm" onClick={onClose} />
    <div className="relative w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl animate-in fade-in zoom-in-95 duration-200">
      <button onClick={onClose} aria-label="Close" className="absolute right-4 top-4 rounded-md p-1 text-muted-foreground transition hover:bg-muted hover:text-foreground"><X className="size-4" /></button>
      {!payment ? <><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Secure crypto checkout</p><h3 className="mt-2 font-display text-2xl font-bold">{amount} for ${price.toFixed(2)}</h3><p className="mt-1 text-sm text-muted-foreground">Choose a crypto network below. NOWPayments handles conversion.</p>
        <form className="mt-5 space-y-4" onSubmit={startPayment}><div className="space-y-1.5"><label htmlFor="ign" className="text-sm font-medium">Minecraft username</label><input id="ign" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="e.g. Steve123" required minLength={3} maxLength={16} pattern="[A-Za-z0-9_.]+" className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/30" /></div>
          <div className="space-y-2"><span className="text-sm font-medium">Payment cryptocurrency</span><div className="grid grid-cols-4 gap-2">{POPULAR.filter((item) => currencies.includes(item)).map((item) => <button type="button" key={item} onClick={() => setCurrency(item)} className={`rounded-lg border px-2 py-2.5 text-xs font-semibold transition hover:-translate-y-0.5 hover:border-primary ${currency === item ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-background text-muted-foreground'}`}>{label(item)}</button>)}<button type="button" onClick={() => setShowOther(!showOther)} className={`flex items-center justify-center gap-1 rounded-lg border px-2 py-2.5 text-xs font-semibold transition hover:border-primary ${showOther ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-background text-muted-foreground'}`}>Other <ChevronDown className={`size-3 transition ${showOther ? 'rotate-180' : ''}`} /></button></div>{showOther && <select aria-label="Other cryptocurrency" value={POPULAR.includes(currency) ? '' : currency} onChange={(e) => setCurrency(e.target.value)} className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/30"><option value="" disabled>Select another cryptocurrency</option>{otherCurrencies.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select>}</div>
          {error && <p className="text-sm text-destructive">{error}</p>}<Button type="submit" disabled={loading} className="w-full font-semibold transition hover:-translate-y-0.5">{loading ? 'Creating secure payment…' : `Continue with ${label(currency)}`}</Button><p className="text-center text-xs text-muted-foreground">You will receive a unique payment address for this order.</p>
        </form></> : <div className="py-2"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Order {payment.orderNumber}</p><h3 className="mt-2 font-display text-2xl font-bold">Send {label(payment.payCurrency ?? currency)}</h3><p className="mt-2 text-sm text-muted-foreground">Send exactly <span className="font-semibold text-foreground">{payment.payAmount} {label(payment.payCurrency ?? currency)}</span> to this address.</p><div className="mt-4 flex items-center gap-2 rounded-lg border border-border bg-background p-3"><span className="min-w-0 flex-1 break-all text-xs text-foreground">{payment.payAddress ?? 'Payment address loading…'}</span><Button type="button" size="icon" variant="outline" onClick={copyAddress} aria-label="Copy payment address">{copied ? <Check className="size-4 text-primary" /> : <Copy className="size-4" />}</Button></div><p className="mt-4 text-center text-sm text-muted-foreground">Status: <span className="font-semibold capitalize text-primary">{status}</span></p>{['finished', 'confirmed'].includes(status) && <p className="mt-3 rounded-lg bg-primary/10 p-3 text-sm text-primary">Payment received. We will deliver {payment.amount} to {username} after confirmation.</p>}<Button className="mt-5 w-full font-semibold" onClick={onClose}>Close</Button></div>}
    </div>
  </div>
}
