import { ArrowUpRight, BadgeCheck, Bot, Coins, CreditCard, MessageCircle, ShieldCheck, Zap } from 'lucide-react'

const coins = ['TRX', 'BTC', 'ETH', 'LTC', 'SOL', 'USDT', 'USDC', 'DOGE']

export function TrustSection() {
  return <section className="mx-auto max-w-6xl px-4 py-12 md:py-16"><div className="mb-8 flex items-center gap-2 text-sm font-medium text-primary"><span className="size-2 rounded-full bg-primary" />Features</div><h2 className="max-w-4xl font-display text-4xl font-bold tracking-tight md:text-6xl">Everything you need, all in one place</h2><p className="mt-4 max-w-2xl text-lg text-muted-foreground">A trusted DonutSMP store built for fast, clear, and secure crypto payments.</p>
    <div className="mt-10 rounded-3xl border border-border bg-card/70 p-6 md:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><div className="flex items-center gap-2 text-sm text-muted-foreground"><CreditCard className="size-4" /> Payment methods</div><h3 className="mt-4 font-display text-3xl font-bold">20+ ways to pay</h3><p className="mt-3 max-w-md text-muted-foreground">Choose the payment method that works for you. We confirm every order manually through Discord.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground">Card</span><span className="rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground">PayPal</span><span className="rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground">Apple Pay</span><span className="rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground">Google Pay</span><span className="rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground">Crypto</span></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><PaymentBadge label="Apple Pay" mark="" /><PaymentBadge label="Google Pay" mark="G" /><PaymentBadge label="PayPal" mark="P" /><PaymentBadge label="Card" mark="•••" />{coins.map((coin) => <PaymentBadge key={coin} label={coin} mark={coin.slice(0, 1)} crypto />)}</div></div></div>
    <div className="mt-4 grid gap-4 md:grid-cols-3"><FeatureCard icon={<Zap />} eyebrow="Delivery" title="Instant status updates" copy="After you pay, our team confirms the order and handles delivery manually through Discord." /><FeatureCard icon={<Coins />} eyebrow="Clear pricing" title="Know what you pay" copy="Your USD total is locked before checkout, with no surprise exchange-rate math." /><FeatureCard icon={<ShieldCheck />} eyebrow="Trust" title="Protected checkout" copy="Secrets stay server-side, payments are signed, and every order is tracked." /></div>
  </section>
}
function PaymentBadge({ label, mark, crypto = false }: { label: string; mark: string; crypto?: boolean }) { return <div className={`flex items-center gap-2 rounded-xl border px-3 py-4 text-sm font-semibold transition-transform duration-300 hover:-translate-y-1 ${crypto ? 'border-primary/25 bg-primary/5' : 'border-border bg-background'}`}><span className={`grid size-8 place-items-center rounded-full text-xs ${crypto ? 'bg-primary/15 text-primary' : 'bg-muted text-foreground'}`}>{mark}</span>{label}</div> }

function FeatureCard({ icon, eyebrow, title, copy }: { icon: React.ReactNode; eyebrow: string; title: string; copy: string }) { return <div className="rounded-2xl border border-border bg-card p-6"><div className="mb-12 flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">{icon}</div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">{eyebrow}</p><h3 className="mt-2 font-display text-2xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{copy}</p></div> }
